
spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 8721

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8711/eureka}
  instance:
    preferIpAddress: true